- name: Shibboleth SP | mpassID | clean |
  xml:
    xpath: "{{ shibsp_item }}"
    state: "absent"
    file: "/etc/shibboleth/shibboleth2.xml"
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
  loop_control:
    loop_var: shibsp_item
  with_items:
    - '/x:SPConfig/x:ApplicationDefaults/x:MetadataProvider[@url="{{ shibbolethsp_mpassidmd }}"]'

- name: Shibboleth SP | mpassID | Metadata | Configure
  xml:
    file: "/etc/shibboleth/shibboleth2.xml"
    xpath: "//x:SPConfig/x:ApplicationDefaults/x:Errors"
    insertafter: yes
    pretty_print: yes
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
    add_children:
      - MetadataProvider:
          type: "XML"
          url: "{{ shibbolethsp_mpassidmd }}"
          backingFilePath: "mpassid-metadata.xml"
          reloadInterval: "3600"
   

