- name: Shibboleth SP | Metadata | suomi.fi | Configure
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "        <!-- {mark} Ansible managed - suomi.fi test metadata -->"
    insertbefore: "<!-- Example of remotely supplied batch of signed metadata. -->"
    content: |2
              <MetadataProvider type="XML" url="{{ shibbolethsp_suomifimd }}" backingFilePath="{{ shibbolethsp_suomifimd |Â basename }}" reloadInterval="3600">
              </MetadataProvider>
   

- name: Shibboleth SP | Metadata | suomi.fi | Configure | Certs start
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "        <!-- {mark} Ansible managed - Virtu keys mapping-->"
    insertbefore: "<!-- Simple file-based resolvers for separate signing/encryption keys. -->"
    content: |2
            <RelyingParty Name="https://uusi.tunnistus.fi/idp1" keyName="vrk-cert"/>