- name: Shibboleth SP | Metadata | Virtu | Configure
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "        <!-- {mark} Ansible managed - Virtu metadata -->"
    insertbefore: "<!-- Example of remotely supplied batch of signed metadata. -->"
    content: |2
              <MetadataProvider type="XML" url="{{ shibbolethsp_virtumd }}" backingFilePath="{{ shibbolethsp_virtumd | basename }}" reloadInterval="3600">
                <MetadataFilter type="Signature" certificate="/etc/pki/tls/certs/{{ shibbolethsp_virtucrt | basename }}"/>
                <MetadataFilter type="RequireValidUntil" maxValidityInterval="2592000"/>
              </MetadataProvider>
   
- name: Shibboleth SP | Metadata | Virtu | Download | Certificate
  get_url: url={{ shibbolethsp_virtucrt }} dest=/etc/pki/tls/certs/{{ shibbolethsp_virtucrt | basename }} mode=0755

- name: Shibboleth SP | Metadata | Virtu | Configure | Certs start
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "        <!-- {mark} Ansible managed - Virtu keys chaining start-->"
    insertafter: "<!-- Simple file-based resolvers for separate signing/encryption keys. -->"
    content: |2
            <RelyingParty Name="virtu" keyName="vrk-cert"/>
            <CredentialResolver type="Chaining">
            <CredentialResolver type="File" key="/etc/pki/tls/private/{{ shibbolethsp_fqdn }}.saml.virtu.key" certificate="/etc/pki/tls/certs/{{ shibbolethsp_fqdn }}.saml.virtu.crt" keyName="vrk-cert"/>

- name: Shibboleth SP | Metadata | Virtu | Configure | Certs end
  blockinfile:
    dest: /etc/shibboleth/shibboleth2.xml
    marker: "        <!-- {mark} Ansible managed - Virtu keys chaininig end -->"
    insertbefore: "</ApplicationDefaults>"
    content: |2
            </CredentialResolver>


